version: '3.8'

services:
  tpp_poc_db:
    build:
      context: ./db
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

  tpp_poc_scripts:
    build:
      context: ./scripts
    env_file:
      - .env
    depends_on:
      - tpp_poc_db